import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="max-h-fit min-h-screen p-2 dark"
    >
      <body className="min-h-full flex flex-col dark:text-white dark:bg-black bg-white">
        <div className="relative w-full flex items-center justify-center">
        <Navbar/>
        </div>
        {children}
        </body>
    </html>
  );
}
