import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("max-h-fit min-h-screen p-2 dark", "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col dark:text-white dark:bg-black bg-white">
        <div className="relative w-full flex items-center justify-center">
        <Navbar/>
        </div>
        {children}
        </body>
    </html>
  );
}
